{
 "title": "Mesos Cluster Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": "label_values(mesos_slave_executor_state, job)"
   },
   {
    "name": "framework_id",
    "label": "Framework ID",
    "query": "label_values(mesos_agent_processes{job=~\"$job\"}, framework_id)"
   }
  ]
 },
 "panels": [
  { "title": "Agent 资源使用总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mesos Agent 资源使用总览",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(mesos_slave_mem_bytes*1024) by(slave)"
    },
    {
     "expr": "avg(mesos_slave_mem_used_bytes*1024) by(slave)"
    },
    {
     "expr": "avg(mesos_slave_cpus{slave!=\"\"}) by(slave)"
    },
    {
     "expr": "avg(mesos_slave_cpus_used) by(slave)"
    },
    {
     "expr": "avg(mesos_slave_disk_bytes*1024) by(slave)"
    },
    {
     "expr": "avg(mesos_slave_disk_used_bytes*1024) by(slave)"
    },
    {
     "expr": "sum(time() - mesos_master_uptime_seconds) by(slave)"
    }
   ]
  },
  {
   "title": "Agent CPU 分配",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "C" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_slave_cpus_used) by(slave)    ",
     "legendFormat": "{{slave}}"
    }
   ]
  },
  {
   "title": "Agent 内存分配",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "avg(mesos_slave_mem_used_bytes/1024/1024) by(slave)",
     "legendFormat": "{{slave}}"
    }
   ]
  },
  { "title": "Agent 任务数统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Agent 列表",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    { "expr": "mesos_slave_registered" }
   ]
  },
  {
   "title": "Agent 运行任务数（实时统计）",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "mesos_slave_task_states_current{state='running'}"
    }
   ]
  },
  {
   "title": "Agent 运行任务数趋势图",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mesos_slave_task_states_current{state='running'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Framework 资源使用总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "CPU Usage（Framework ID：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "C" }
   ],
   "targets": [
    {
     "expr": "sum (irate(mesos_agent_cpu_user_seconds_total{framework_id=\"$framework_id\"}[5m]))",
     "legendFormat": "{{framework_id}}(used)"
    },
    {
     "expr": "sum (mesos_agent_cpus_limit{framework_id=\"$framework_id\"})",
     "legendFormat": "{{framework_id}}(alloc)"
    }
   ]
  },
  {
   "title": "Memory Usage（Framework ID：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "sum (mesos_agent_mem_rss_bytes{framework_id=\"$framework_id\"})/1024/1024/1024",
     "legendFormat": "{{framework_id}}(used)"
    },
    {
     "expr": "sum (mesos_agent_mem_limit_bytes{framework_id=\"$framework_id\"})/1024/1024/1024",
     "legendFormat": "{{framework_id}}(alloc)"
    }
   ]
  },
  {
   "title": "CPU Usage Rate（Framework ID：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum (irate(mesos_agent_cpu_user_seconds_total{framework_id=\"$framework_id\"}[5m])) / sum (mesos_agent_cpus_limit{framework_id=\"$framework_id\"}) * 100",
     "legendFormat": "usage rate"
    }
   ]
  },
  {
   "title": "Memory Usage Rate（Framework ID：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "(sum (mesos_agent_mem_rss_bytes{framework_id=\"$framework_id\"})/1024/1024/1024)/(sum (mesos_agent_mem_limit_bytes{framework_id=\"$framework_id\"})/1024/1024/1024) * 100",
     "legendFormat": "usage rate"
    }
   ]
  },
  { "title": "任务资源使用总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU Usage Per Task（Framework：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "C" }
   ],
   "targets": [
    {
     "expr": "irate(mesos_agent_cpu_user_seconds_total{framework_id=\"$framework_id\"}[5m])",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Usage Per Task（Framework：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "mesos_agent_mem_rss_bytes{framework_id=\"$framework_id\"}/1024/1024/1024",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU Alloc Per Task（Framework：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "C" }
   ],
   "targets": [
    {
     "expr": "mesos_agent_cpus_limit{framework_id=\"$framework_id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Alloc Per Task（Framework：$framework_id）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "GB" }
   ],
   "targets": [
    {
     "expr": "mesos_agent_mem_limit_bytes{framework_id=\"$framework_id\"}/1024/1024/1024",
     "legendFormat": "{{id}}"
    }
   ]
  }
 ]
}